### ISSUE TITLE
Cannot compile programs that vendor GopherJS

### ISSUE THREAD

**Issue by johanbrandhorst** [dave/jsgo#13]
GopherJS recently recieved support for vendoring, and I updated my johanbrandhorst/grpcweb-example to vendor the GopherJS compiler. However, now I can't compile the client package anymore:

https://compile.jsgo.io/johanbrandhorst/grpcweb-example/client

It returns `Error: vendoring github.com/gopherjs/gopherjs/js package is not supported, see https://github.com/gopherjs/gopherjs/issues/415`.

Presumably this should just be a matter of upgrading the compiler?

**Comment by dave** [comment]
Hmm this is a tricky one. I'm using a forked and significantly tweaked version of the GopherJS build package ([here](https://github.com/dave/jsgo/tree/master/builder)). The additions to that package were non-trivial and will take a little time for me to work out how I can fix the jsgo version. I'll have spotty internet for a few weeks but I'll take a look as soon as I can.

**Comment by dave** [comment]
(the jsgo initialisation script copies `github.com/gopherjs/gopherjs/js` and `github.com/gopherjs/gopherjs/nosync` into it's own virtual goroot, so they're always there... not sure how this affects things... Maybe I don't need this gopherjspkg.FS complexity... Hmm

**Comment by dave** [comment]
OK I've got the builder package up to date with the latest changes in the GopherJS build package, and it seems to build your example ok... Can you check it works as you're expecting?

**Comment by johanbrandhorst** [comment]
Seems to be all working again, thanks for the quick fix!
