### ISSUE TITLE
Error message at 2048

### ISSUE THREAD

**Issue by hajimehoshi** [dave/jsgo#15]
https://play.jsgo.io/github.com/hajimehoshi/ebiten/examples/2048

```
package github.com/go-gl/gl/v2.1/gl: build constraints exclude all Go files in gopath/src/github.com/go-gl/gl/v2.1/gl
```

```
websocket closed but archives not updated
```

That's odd since Ebiten should not require go-gl on browsers. I'd be happy if you could confirm this. Thank you!

**Comment by dave** [comment]
Aaah ok so today I removed the `js` build tag from jsgo... It broke compatibility with go1.11... i think here:

https://github.com/hajimehoshi/ebiten/blob/063edfcc4a3d0ca5632d84910b3181d3bc81ed88/internal/opengl/context_desktop.go#L16

you need to add:

`// +build !gopherjs`

or

`// +build !jsgo`

... I'll take another look to see if I was right to remove `js`...

**Comment by hajimehoshi** [comment]
To represent GopherJS, `// +bulid js` && `// +build !wasm` should work, right?

**Comment by dave** [comment]
Hang on - I'm going to have a good look through the code and work out where this is coming from... Bear with me...

**Comment by dave** [comment]
OK I think I fixed it... Give this a try...

**Comment by hajimehoshi** [comment]
Yes, this has been fixed. Thank you!
