### ISSUE TITLE
go generate at $GOPATH/src/github.com/dave/jsgo/initialise failed

### ISSUE THREAD

**Issue by hajimehoshi** [dave/jsgo#19]
```
hajimehoshi@Hajimes-MacBook-Pro ~/go/src/github.com/dave/jsgo/initialise
$ GOPATH=~/go go generate
Loading...
Compiling: archive/tar (minified)
2018/12/26 01:41:20 goroot/src/reflect/value.go:673:60: cannot use t (variable of type *rtype) as *funcType value in argument to funcLayout
exit status 1
generate.go:3: running "go": exit status 1
```

**Comment by dave** [comment]
What Go version are you using?

**Comment by hajimehoshi** [comment]
go version go1.11.2 darwin/amd64

**Comment by dave** [comment]
OK I was on `go1.11`... I just upgraded to `go1.11.4` and I'm getting the same error... I'll have a look into it...

**Comment by dave** [comment]
Give it a try now... The fix was in `github.com/dave/services`. I've upgraded `services` and `jsgo` to modules so you should be able to do a `go get` and it might work now.

**Comment by hajimehoshi** [comment]
OK now this succeeded. Thanks!
