### ISSUE TITLE
Compilation error: Authentication required

### ISSUE THREAD

**Issue by hajimehoshi** [dave/jsgo#21]
https://compile.jsgo.io/github.com/hajimehoshi/examples/raycasting

```
package github.com/hajimehoshi/examples/raycasting: authentication required
```

**Comment by dave** [comment]
github.com/hajimehoshi/examples is giving a 404... typeo somewhere?

**Comment by dave** [comment]
https://compile.jsgo.io/github.com/hajimehoshi/ebiten/examples/raycasting is what you want I think

**Comment by hajimehoshi** [comment]
Ah, that's right.. Sorry for disturbing. That's embarrassing.

It'd be better if I could see a better error message.
