### ISSUE TITLE
playground: 'runtime not found' error

### ISSUE THREAD

**Issue by hajimehoshi** [dave/jsgo#9]
https://jsgo.io/dave/jsgo/playground#50da9bc755bcb33603cf45c32d7d66214d2bbb20

Executed an almost empty Go program.

**Comment by dave** [comment]
Yeah it probably needs the runtime, but without any imports it probably doesn't bother going to the server to pick up dependencies. This should be an easy fix.

**Comment by dave** [comment]
Fixed!
